version: 0.2

phases:
  install:
    commands:
      - echo Install Node 14...
      - curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
      - apt install -y nodejs
      - echo Install latest npm...
      - npm install -g npm@latest
      - apt install build-essential
      - echo Nodejs version...
      - node --version
      - echo npm version... 
      - npm --version

  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building...
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build