version: 0.2

phases:
  install:
    commands:
      - echo Install Node 14...
      - curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
      - apt install -y nodejs
      - echo Install latest npm...
      - npm install -g npm@7.5.4
      - apt install build-essential

  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building...
      - npm run build
artifacts:
  files:
    - public/**/*
    - src/**/*
    - package.json
    - appspec.yml
    - scripts/**/*